import './js/header';
import './js/mobile-menu';
import './js/about-me';
import './js/projects';
import './js/faq';
import './js/covers.js';
import './js/reviews';
import './js/work-together';
import './js/swiper';
